name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.deploy_key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # install
      - run: npm ci
      # Deploy
      - run: cd . && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@kpogodin.ru:/home/apps/kpogodin-server/ 

  ssh_comands:
    name: ssh_comands
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: | 
          cd /home/apps/kpogodin-server && cp nginx.conf /etc/nginx/sites-available 
          cd /etc/nginx/sites-available && rm default && mv nginx.conf default
          service nginx restart
          pm2 kill
          cd /home/apps/kpogodin-server && pm2 start "npm run start"
