# name: remote ssh command
# on:
#   push:
#     branches:
#       - master

# jobs:

#   build:
#     name: ssh_comands
#     runs-on: ubuntu-latest
#     steps:
#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USER_NAME }}
#         key: ${{ secrets.DEPLOY_KEY }}
#         script: | 
#           whoami
#           cd /home/apps/kpogodin-server && mkdir TEST